opensagres/xdocreport

document/fr.opensagres.xdocreport.document.docx/src/main/java/fr/opensagres/xdocreport/document/docx/textstyling/DocxDocumentHandler.java

<sub> and <sup> elements should be handled even they are not in bold,italics, underline or strike elements, so on I changed one line at processRunProperties method
Ps. I am novice at git open source contribution, sorry If something is wrong.

sub and sup elements handle

---

thirdparties-extension/org.odftoolkit.odfdom.converter.pdf.itext5/src/main/java/org/odftoolkit/odfdom/converter/pdf/internal/stylable/StylableParagraph.java

Inserting Chunk.NEWLINE instead of new Chunk( ODFUtils.TAB_STR ) when the paragraph is empty.

#114 No blank lines on ODT->PDF with itext5

---

thirdparties-extension/fr.opensagres.odfdom.converter.xhtml/pom.xml
thirdparties-extension/fr.opensagres.odfdom.converter.xhtml/src/main/java/fr/opensagres/odfdom/converter/internal/xhtml/ElementVisitorForXHTML.java
thirdparties-extension/fr.opensagres.odfdom.converter.xhtml/src/main/java/fr/opensagres/odfdom/converter/xhtml/XHTMLOptions.java
thirdparties-extension/fr.opensagres.odfdom.converter.xhtml/src/main/java/fr/opensagres/xdocreport/xhtml/extension/XHTMLConstants.java
thirdparties-extension/fr.opensagres.odfdom.converter.xhtml/src/test/java/org/odftoolkit/odfdom/converter/xhtml/XHTMLConverterTestCase.java

Hello!
Add a option 'exportImageAsBase64' for XHTMLOptions., then the images in the ODT will export as base64 data in the HTML when convert ODT to HTML.
I think it is useful. 
Thinks.

Add option for XHTMLOptions to export image as base64 data

---

thirdparties-extension/fr.opensagres.poi.xwpf.converter.core/src/main/java/fr/opensagres/poi/xwpf/converter/core/ImageManager.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.core/src/main/java/fr/opensagres/poi/xwpf/converter/core/Options.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.xhtml/src/main/java/fr/opensagres/poi/xwpf/converter/xhtml/XHTMLOptions.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.xhtml/src/test/java/org/apache/poi/xwpf/converter/xhtml/XHTMLConverterChineseTestCase.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.xhtml/src/test/java/org/apache/poi/xwpf/converter/xhtml/XHTMLConverterTestCase.java

Hi,
When I use your lib, it takes me some time to understand the functionality of `resolver`, which for conversion of html, resolve the image's src attribute. As far as I understand, the resolver and image extractor can be combined for XHTML, which is easier to understand and write.
So I use one method/class to replace two:
- make `URIResolver` deprecated
- make `setExtractor` protected -- may affect the pdf conversion, but I didn't find any usage for pdf conversion in project
- add `setImageManager`
Thanks.

combine the options of image src resolver and image extractor;

---

gae/fr.opensagres.poi.xwpf.converter.xhtml-gae/pom.xml
thirdparties-extension/fr.opensagres.poi.xwpf.converter.core/pom.xml
thirdparties-extension/fr.opensagres.poi.xwpf.converter.xhtml/pom.xml
thirdparties-extension/fr.opensagres.poi.xwpf.converter.xhtml/src/main/java/fr/opensagres/poi/xwpf/converter/xhtml/Base64EmbedImgManager.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.xhtml/src/main/java/fr/opensagres/poi/xwpf/converter/xhtml/XHTMLConstants.java

Hi,
This the solution I used when I using your lib to convert docx to html and need to embed image into html. It take me some time to figure it out. But it has some flaws:
- can't specify MIME type, even though the browser still show the image
- can't easily manipulate image, like compress them
If you think this simple solution isn't enough, I may change the `XWPFDocumentVisitor` and change the extractor's interfaces.
Thanks.

add the simple implementations to embed image in html;

---

template/fr.opensagres.xdocreport.template.velocity/src/main/resources/xdocreport-velocity.properties

Before this patch, the `introspector.restrict.classes` property appeared multiple times in the config file and the behaviour in this case is to take the value of the last occurence of the property.
With my patch, all the classes in this list are now blacklisted by velocity.

Fix introspector class blacklisting in velocity config

---

template/fr.opensagres.xdocreport.template/src/main/java/fr/opensagres/xdocreport/template/internal/DynamicBean.java

When evaluating a dotted key, the next segment should always be evaluated based on the previous, but now it's always done on the root. E.g. "A.B.C" is evaluated as "A.C". This PR fixes this.

Fix recursive lookup of dotted keys.

---

thirdparties-extension/fr.opensagres.poi.xwpf.converter.core/src/main/java/fr/opensagres/poi/xwpf/converter/core/utils/ColorHelper.java

Please, if approved, could you add this fix also at version 1.0.7? Thank you!

Fixed invalid getColor when it's empty

---

document/fr.opensagres.xdocreport.document/src/main/java/fr/opensagres/xdocreport/document/images/SimpleImageInfo.java
document/fr.opensagres.xdocreport.document/src/test/java/fr/opensagres/xdocreport/document/images/FileImageProviderTestCase.java
document/fr.opensagres.xdocreport.document/src/test/java/fr/opensagres/xdocreport/document/images/ImageInfoTestCase.java

When trying to get image info of an AbstractInputStreamImageProvider, the provided stream is never closed.

Close input stream of an image provider after loading its info

---

document/fr.opensagres.xdocreport.document.docx/src/main/java/fr/opensagres/xdocreport/document/docx/preprocessor/sax/MergefieldBufferedRegion.java
integrationtests/fr.opensagres.xdocreport.core.test/src/test/java/fr/opensagres/xdocreport/document/docx/preprocessor/Issue277.java

recover text styling for split instrText fields by re-evaluating the text styling in MergefieldBufferedRegion in case of null-styles as one way to fix issue #277

recover text styling for split instrText fields (issue #277)

---

document/fr.opensagres.xdocreport.document.docx/pom.xml
document/fr.opensagres.xdocreport.document.docx/src/test/java/fr/opensagres/xdocreport/document/docx/DocxReportTestCase.java
document/fr.opensagres.xdocreport.document/src/main/java/fr/opensagres/xdocreport/document/AbstractXDocReport.java

improve AbstractXDocReport.preprocess by directly calling doPreprocessorIfNeeded. the old approach only worked if cacheOriginalDocument is true; otherwise getOriginalDocumentArchive returns null, causing an NPE.

AbstractXDocReport: improve preprocess

---

thirdparties-extension/fr.opensagres.poi.xwpf.converter.core/src/main/java/fr/opensagres/poi/xwpf/converter/core/MasterPageManager.java

This allows for headers and footers to be inherited from the previous
sections, see http://officeopenxml.com/WPSectionHeaderReference.php. It
also allows for docx documents that do not specify types for sections to
work such as those created from Java.

inherit headers and footers

---

thirdparties-extension/fr.opensagres.poi.xwpf.converter.core/src/main/java/fr/opensagres/poi/xwpf/converter/core/XWPFDocumentVisitor.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.pdf.itext5/src/main/java/fr/opensagres/poi/xwpf/converter/pdf/internal/elements/StylableDocument.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.pdf/src/main/java/fr/opensagres/poi/xwpf/converter/pdf/internal/elements/StylableDocument.java

Avoid NPE when numbering is missing.
It seems that this issue can occur when a user has copied a paragraph
from a numbered list to a docx without any lists.

Missing numbering

---

thirdparties-extension/fr.opensagres.poi.xwpf.converter.core/src/main/java/fr/opensagres/poi/xwpf/converter/core/XWPFDocumentVisitor.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.pdf.itext5/src/main/java/fr/opensagres/poi/xwpf/converter/pdf/internal/PdfMapper.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.pdf/src/main/java/fr/opensagres/poi/xwpf/converter/pdf/internal/PdfMapper.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.xhtml/src/main/java/fr/opensagres/poi/xwpf/converter/xhtml/internal/XHTMLMapper.java

This solves the issue #264
I was facing the same issue, and from investigation looks like background color for text is not applied when using MS Word feature Text Highlight. But if you highlight text using Shadow feature, it works just fine. 
The problem was because visitor skips runs which contains some styles, therefore do not create pdf chunks at all. I have added override for visitStyleText which reuses the same functionality as in visitText. Not sure why we have two PdfMappers so added to both.
File to reproduce,  [xdocreport_background_text.docx](https://github.com/opensagres/xdocreport/files/2090665/xdocreport_background_text.docx)
All three text runs should appear in generated pdf, like in screenshot below

Added override for visitStyleText

---

thirdparties-extension/fr.opensagres.poi.xwpf.converter.pdf.itext5/src/main/java/fr/opensagres/poi/xwpf/converter/pdf/internal/elements/StylableColumnText.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.pdf.itext5/src/main/java/fr/opensagres/poi/xwpf/converter/pdf/internal/elements/StylableDocument.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.pdf.itext5/src/main/java/fr/opensagres/poi/xwpf/converter/pdf/internal/elements/StylableDocumentSection.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.pdf/src/main/java/fr/opensagres/poi/xwpf/converter/pdf/internal/elements/StylableColumnText.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.pdf/src/main/java/fr/opensagres/poi/xwpf/converter/pdf/internal/elements/StylableDocument.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.pdf/src/main/java/fr/opensagres/poi/xwpf/converter/pdf/internal/elements/StylableDocumentSection.java

This helps to avoid blank pages at the end if sections by ignoring pages
that only have blank space. Some of the new lines have been added by
XWPFDocumentVisitor.isAddNewLine returning true even when the page or
table is the last one in the section. While it would be possible to fix
XWPFDocumentVisitor.isAddNewLine not to add these, this commit also
solves the issue if the docx had an extra new lines at the end of the
page and the conversion to pdf had more space than the original docx.

Avoid blank pages at the end of sections.

---

document/fr.opensagres.xdocreport.document.odt/src/main/java/fr/opensagres/xdocreport/document/odt/ODTConstants.java
document/fr.opensagres.xdocreport.document.odt/src/main/java/fr/opensagres/xdocreport/document/odt/ODTUtils.java
document/fr.opensagres.xdocreport.document.odt/src/main/java/fr/opensagres/xdocreport/document/odt/preprocessor/ODTAnnotationParsingHeler.java
document/fr.opensagres.xdocreport.document.odt/src/main/java/fr/opensagres/xdocreport/document/odt/preprocessor/ODTBufferedDocumentContentHandler.java
document/fr.opensagres.xdocreport.document.odt/src/test/java/fr/opensagres/xdocreport/document/odt/preprocessor/ODTAnnotationParsingHelerTest.java
document/fr.opensagres.xdocreport.document/src/main/java/fr/opensagres/xdocreport/document/preprocessor/sax/BufferedDocumentContentHandler.java
document/fr.opensagres.xdocreport.document/src/main/java/fr/opensagres/xdocreport/document/preprocessor/sax/TransformedBufferedDocumentContentHandler.java
integrationtests/fr.opensagres.xdocreport.core.test/src/test/java/fr/opensagres/xdocreport/document/odt/preprocessor/ODTPreprocessorAnnotationRangeTestCase.java
integrationtests/fr.opensagres.xdocreport.core.test/src/test/java/fr/opensagres/xdocreport/document/odt/preprocessor/ODTPreprocessorAnnotationTestCase.java

<office:annotation> is now treated as velocity script container with ability to
iterate over table-row, list-item and sections. Also can be treated as
the way of substituting parts of text. All this operations are desgn to
be xml safe.

Treated ODT annotations like script container.

---

template/fr.opensagres.xdocreport.template.velocity/src/main/java/fr/opensagres/xdocreport/template/velocity/ModelFieldType.java
template/fr.opensagres.xdocreport.template.velocity/src/main/java/fr/opensagres/xdocreport/template/velocity/VelocityDocumentFormatter.java
template/fr.opensagres.xdocreport.template.velocity/src/test/java/fr/opensagres/xdocreport/template/velocity/VelocityFieldsExtractorTestCase.java
template/fr.opensagres.xdocreport.template.velocity/src/test/java/fr/opensagres/xdocreport/template/velocity/VelocityTemplateEngineDocumentFormatterTestCase.java

This fixes #237 and #283. Now preprocessor replaces all found model tokens (prefixed with $ or $! or $!{ or ${). Before preprocessor was replacing only model fields of one type (first found).

Better model field type handling in Velocity

---

document/fr.opensagres.xdocreport.document.docx/src/main/java/fr/opensagres/xdocreport/document/docx/preprocessor/sax/DocXBufferedDocumentContentHandler.java
document/fr.opensagres.xdocreport.document.odt/src/main/java/fr/opensagres/xdocreport/document/odt/preprocessor/ODTBufferedDocumentContentHandler.java
document/fr.opensagres.xdocreport.document.pptx/src/main/java/fr/opensagres/xdocreport/document/pptx/preprocessor/PPTXSlideContentHandler.java
document/fr.opensagres.xdocreport.document/src/main/java/fr/opensagres/xdocreport/document/preprocessor/sax/TransformedBufferedDocumentContentHandler.java
template/fr.opensagres.xdocreport.template/src/main/java/fr/opensagres/xdocreport/template/formatter/FieldsMetadata.java

When using tables, it is sometimes very convenient to insert code not only before row but also before whole table (and after table) without inserting it and new line before the table (such as when table is supposed to start at the beginning of the page). Problem with only before-row is that it will insert start of table every time. So I created this quickfix that adds two new macros `@before-table` and `@after-table` with same usage as before-row/after-row but code is inserted directly before and after table.
Example usage:
[xtest.zip](https://github.com/opensagres/xdocreport/files/2296943/xtest.zip)
Btw word will merge tables near each other which is fine. When you unzip created document, you can see that there are separate table xml elements.

Added macro @before-table and @after-table

---

thirdparties-extension/fr.opensagres.poi.xwpf.converter.core/src/main/java/fr/opensagres/poi/xwpf/converter/core/utils/XWPFTableUtil.java

As the logic in the StylableTableCell classes expects the border size to be set in case TableCellBorder::hasBorder is true since commit 3a7bb027f930a77e38d825a87085142e96e8e1c5, we should set that value in case the xml doesn't contain one.
This is e.g. the case when the table was created using apache poi, c.f. <https://github.com/apache/poi/blob/179e81c4a44ee303c0300533fe5b43ac660705a1/src/ooxml/java/org/apache/poi/xwpf/usermodel/XWPFTable.java#L199-L205>

prevent NPE by using default border size (1/4 pt) in case no Sz is given

---

integrationtests/fr.opensagres.xdocreport.osgi.integrationtests/src/test/java/fr/opensagres/xdocreport/osgi/integrationtests/ConverterTest.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.core/src/main/java/fr/opensagres/poi/xwpf/converter/core/ImageShapeStyle.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.core/src/main/java/fr/opensagres/poi/xwpf/converter/core/XWPFDocumentVisitor.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.pdf.itext5/src/main/java/fr/opensagres/poi/xwpf/converter/pdf/internal/PdfMapper.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.pdf/src/main/java/fr/opensagres/poi/xwpf/converter/pdf/internal/PdfMapper.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.xhtml/src/main/java/fr/opensagres/poi/xwpf/converter/xhtml/internal/XHTMLMapper.java

Added VML support in XWPF to PDF Converter, Issue #350 
Documents having pictures/images in VML format in DOCX doesn't show in the result PDF document when DOCX converted to PDF. This issue has been fixed.
Fix has provided with this pull request.
https://github.com/opensagres/xdocreport/issues/350

Support vml xwpf to pdf converter

---

document/fr.opensagres.xdocreport.document.docx/src/main/java/fr/opensagres/xdocreport/document/docx/textstyling/DocxColorGenerator.java
document/fr.opensagres.xdocreport.document.docx/src/main/java/fr/opensagres/xdocreport/document/docx/textstyling/DocxDocumentHandler.java
document/fr.opensagres.xdocreport.document.docx/src/test/java/fr/opensagres/xdocreport/document/docx/textstyling/DocxColorGeneratorTest.java
document/fr.opensagres.xdocreport.document.docx/src/test/java/fr/opensagres/xdocreport/document/docx/textstyling/DocxDocumentHandlerTestCase.java
document/fr.opensagres.xdocreport.document/src/main/java/fr/opensagres/xdocreport/document/textstyling/html/HTMLColorParser.java
document/fr.opensagres.xdocreport.document/src/main/java/fr/opensagres/xdocreport/document/textstyling/html/StylesHelper.java
document/fr.opensagres.xdocreport.document/src/main/java/fr/opensagres/xdocreport/document/textstyling/properties/Color.java
document/fr.opensagres.xdocreport.document/src/main/java/fr/opensagres/xdocreport/document/textstyling/properties/ContainerProperties.java
document/fr.opensagres.xdocreport.document/src/test/java/fr/opensagres/xdocreport/document/textstyling/html/HTMLColorParserTest.java
document/fr.opensagres.xdocreport.document/src/test/java/fr/opensagres/xdocreport/document/textstyling/html/StylesHelperTest.java

The color attribute was missing in the supported styles. This pull request adds the missing support.
i. e.
`<span style="color: rgb(255, 0, 0);">Hello World</span>` or
`<span style="color: #FF0000;">Hello World</span>`
now produces 
`<w:color w:val="FF0000"/>`
in the docx xml.

Adds "color" to the supported styles of text styling

---

document/fr.opensagres.xdocreport.document/src/main/java/fr/opensagres/xdocreport/document/textstyling/Style.java

In the documentation of `fr.opensagres.xdocreport.core.io.IOUtils#toString(java.io.InputStream)` it mentions
```
Get the contents of an <code>InputStream</code> as a String using the default character encoding of the platform.
```
In Windows, at least, the default character encoding will not be UTF-8. So XML files, and XML fragments using this method may not be correct. Of particular note is the XML fragment located in the `fr.opensagres.xdocreport.document.docx` project at 
`fr.opensagres.xdocreport.document.docx.textstyling.XDocReport_AbstractNum_bullet.xml` which contains characters that are not properly resolved using the default charset on Windows.
By forcing the charset to be UTF-8, the problem I encountered on Windows (and any other platforms) is resolved.
This problem manifests …

Force the charset for reading XML files and fragments to be UTF-8.

---

thirdparties-extension/fr.opensagres.poi.xwpf.converter.core/src/main/java/fr/opensagres/poi/xwpf/converter/core/ListContext.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.xhtml/src/main/java/fr/opensagres/poi/xwpf/converter/xhtml/internal/XHTMLMapper.java

In my case I see that tab was missed in output HTML (no space between words).
This is because both currentParagraph and tabs were not empty.
I added fix for this case.

Fix for missed tab in HTML

---

thirdparties-extension/fr.opensagres.poi.xwpf.converter.core/src/main/java/fr/opensagres/poi/xwpf/converter/core/ListContext.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.core/src/main/java/fr/opensagres/poi/xwpf/converter/core/ListItemContext.java

If numbering in word doc was disabled (Numbering none) then Word doesn't show head numbers.
But converter from Word to Html adds them.
This is because code supports only a few STNumberFormat formats.
Two new formats were added DECIMAL_ZERO and NONE.
Now I see correct html (no numbers in list when they are disabled).

new STNumberFormat were added

---

template/fr.opensagres.xdocreport.template.velocity/pom.xml
template/fr.opensagres.xdocreport.template.velocity/src/main/java/fr/opensagres/xdocreport/template/velocity/VelocityFieldsExtractor.java
template/fr.opensagres.xdocreport.template.velocity/src/main/java/fr/opensagres/xdocreport/template/velocity/cache/XDocReportEntryResourceLoader.java
template/fr.opensagres.xdocreport.template.velocity/src/main/java/fr/opensagres/xdocreport/template/velocity/discovery/VelocityTemplateEngineDiscovery.java
template/fr.opensagres.xdocreport.template.velocity/src/main/java/fr/opensagres/xdocreport/template/velocity/internal/XDocReportEscapeReference.java

+ Remove the null log chute code because that seems no longer needed since velocity 2.3 uses slf4j
(and that no longer compiles)

Update to velocity 2.3 resolves: #238

---

template/fr.opensagres.xdocreport.template.velocity/src/main/java/fr/opensagres/xdocreport/template/velocity/VelocityDocumentFormatter.java
template/fr.opensagres.xdocreport.template.velocity/src/test/java/fr/opensagres/xdocreport/template/velocity/VelocityTemplateEngineDocumentFormatterExtractDirectivesTestCase.java

Fix #512:
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0    
at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)    
at java.base/java.lang.String.charAt(String.java:693)    
at xxxxx/fr.opensagres.xdocreport.template.velocity.VelocityDocumentFormatter.parseStartLoop(VelocityDocumentFormatter.java:396)
Thrown when #foreach expressions have a space after opening parenthesis like:
#foreach( $d in $developers )

String index out of range: when #foreach has space after parenthesis

---

template/fr.opensagres.xdocreport.template.velocity/src/main/java/fr/opensagres/xdocreport/template/velocity/discovery/VelocityTemplateEngineDiscovery.java

Due to Velocity 2.3 migration, this PR will set properties to maximize backward compatibility of previous XDoxReport Velocity 1 templates with Velocity 2
#238

Set properties to ensure best compatibility with existing template

---

thirdparties-extension/fr.opensagres.odfdom.converter.pdf/src/main/java/fr/opensagres/odfdom/converter/pdf/internal/stylable/StylableDocumentSection.java

Prevents content overflow in fr.opensagres.odfdom.converter.pdf.internal.stylable.StylableDocument#simulateText when adding content that should fit

Fix for table contents printed twice (second on new page)

---

template/fr.opensagres.xdocreport.template.freemarker/pom.xml

This change in version on the FreeMarker Dependency will allow the use of multiple new functionalities.
On the FreeMarker [Download Page](https://freemarker.sourceforge.io/freemarkerdownload.html), it marks the version 2.3.20 as the latest stable version, but as can be seen on the releases on the [Version History Page](https://freemarker.apache.org/docs/app_versions.html) on their Website, that information is not updated.

Updated the FreeMarker Dependency from 2.3.20 to 2.3.28

---

core/pom.xml
document/fr.opensagres.xdocreport.document.tools/pom.xml
integrationtests/fr.opensagres.xdocreport.core.test/src/test/java/fr/opensagres/xdocreport/core/document/registry/XDocReportRegistryTestCase.java
integrationtests/fr.opensagres.xdocreport.osgi.integrationtests/pom.xml
remoting/fr.opensagres.xdocreport.remoting.converter.server/pom.xml
remoting/fr.opensagres.xdocreport.remoting.reporting.server/pom.xml
template/fr.opensagres.xdocreport.template.velocity/src/main/java/fr/opensagres/xdocreport/template/velocity/discovery/VelocityTemplateEngineDiscovery.java
template/fr.opensagres.xdocreport.template.velocity/src/main/java/fr/opensagres/xdocreport/template/velocity/internal/VelocityTemplateEngine.java
template/fr.opensagres.xdocreport.template.velocity/src/main/resources/xdocreport-velocity.properties

The goal of this merge request is to avoid deprecation message from velocity engine like : 
`15:03:18.178 WARN  org.apache.velocity.deprecation - configuration key 'report.resource.loader.modificationCheckInterval' has been deprecated in favor of 'resource.loader.report.modificationCheckInterval'
15:03:18.184 WARN  org.apache.velocity.deprecation - configuration key 'report.resource.loader.cache' has been deprecated in favor of 'resource.loader.report.cache'
15:03:18.184 WARN  org.apache.velocity.deprecation - configuration key 'resource.loader' has been deprecated in favor of 'resource.loaders'
15:03:18.186 WARN  org.apache.velocity.deprecation - configuration key 'report.resource.loader.class' has been deprecated in favor of 'resource.loader.report.class'
15:03:18.186 WARN …

 avoid usage of deprecated velocity configuration properties

---

thirdparties-extension/fr.opensagres.poi.xwpf.converter.pdf/src/main/java/fr/opensagres/poi/xwpf/converter/pdf/internal/PdfMapper.java
thirdparties-extension/fr.opensagres.poi.xwpf.converter.pdf/src/main/java/fr/opensagres/poi/xwpf/converter/pdf/internal/elements/StylableParagraph.java

 #246: Added better handling for default 'leading' value of a Paragraph.
